---
- name: Etckeeper Playbook
  apt: "pkg=etckeeper state=latest"

- name: Unset for bzr
  replace: dest=/etc/etckeeper/etckeeper.conf regexp='^VCS="bzr"' replace='#VCS="bzr"' 

- name: Set for git
  replace: dest=/etc/etckeeper/etckeeper.conf regexp='^#VCS="git"' replace='VCS="git"' 
  
- stat: path=/etc/.git
  register: check_init
  
- command: "etckeeper init"
  register: inited
  when: check_init.stat.exists == false
 
- command: "etckeeper commit -m Initial"
  when: inited.changed == true

